name: CI

on:
  push:
    branches: ["main"]

env:
  AWS_DEFAULT_REGION: us-east-1

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - run: poetry install --only dev
      - run: make black
      - run: make sort
      - run: make pre-commit
      - run: make complex
      - run: make lint

  unitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - run: poetry install
      - run: make unit

  release:
    runs-on: ubuntu-latest
    needs: [linting, unitTest]
    concurrency: release

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SEMANTIC_RELEASE_GIT_TOKEN }}
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: |
          python -m pip install --upgrade pip
          pip install python-semantic-release==7.34.6
      - run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          semantic-release publish -D commit_author="github-actions <action@github.com>"
        env:
          GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GIT_TOKEN }}
